upload train.csv to the left side

In [1]:
import pandas as pd

df = pd.read_csv('train.csv')

df.head()

,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
0,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5.0,NaN,12.50
1,2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,13 km/kg,1199 CC,88.7 bhp,5.0,8.61 Lakh,4.50
2,3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77 kmpl,1248 CC,88.76 bhp,7.0,NaN,6.00
3,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.2 kmpl,1968 CC,140.8 bhp,5.0,NaN,17.74
4,6,Nissan Micra Diesel XV,Jaipur,2013,86999,Diesel,Manual,First,23.08 kmpl,1461 CC,63.1 bhp,5.0,NaN,3.50

In [2]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5847 entries, 0 to 5846
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         5847 non-null   int64
 1   Name               5847 non-null   object
 2   Location           5847 non-null   object
 3   Year               5847 non-null   int64
 4   Kilometers_Driven  5847 non-null   int64
 5   Fuel_Type          5847 non-null   object
 6   Transmission       5847 non-null   object
 7   Owner_Type         5847 non-null   object
 8   Mileage            5845 non-null   object
 9   Engine             5811 non-null   object
 10  Power              5811 non-null   object
 11  Seats              5809 non-null   float64
 12  New_Price          815 non-null    object
 13  Price              5847 non-null   float64
dtypes: float64(2), int64(3), object(9)
memory usage: 639.6+ KB

        Unnamed: 0         Year  Kilometers_Driven        Seats        Price
count  5847.000000  5847.000000       5.847000e+03  5809.000000  5847.000000
mean   3013.181461  2013.448435       5.841013e+04     5.286452     9.653742
std    1736.398890     3.194949       9.237971e+04     0.806668    11.275966
min       1.000000  1998.000000       1.710000e+02     2.000000     0.440000
25%    1509.500000  2012.000000       3.346750e+04     5.000000     3.550000
50%    3015.000000  2014.000000       5.257600e+04     5.000000     5.750000
75%    4517.500000  2016.000000       7.249050e+04     5.000000    10.250000
max    6018.000000  2019.000000       6.500000e+06    10.000000   160.000000

missing value

In [3]:
df.isnull().sum()

Unnamed: 0              0
Name                    0
Location                0
Year                    0
Kilometers_Driven       0
Fuel_Type               0
Transmission            0
Owner_Type              0
Mileage                 2
Engine                 36
Power                  36
Seats                  38
New_Price            5032
Price                   0
dtype: int64

Q1, a): Missing values were handled based on the nature and proportion of missing data.
For numerical columns such as Mileage, Engine, and Power, missing values were replaced using the median to reduce the effect of outliers. Since some numerical columns (Mileage, Engine, and Power) were stored as strings with units, the mode was temporarily used to fill missing values before converting them into numerical format.
For the Seats column, missing values were filled using the mode since it represents categorical-like discrete data.
The New_Price column had more than 85% missing values, so it was dropped from the dataset to avoid unreliable imputation.

In [4]:
# delete New_Price
df = df.drop(columns=['New_Price'], errors='ignore')

df['Mileage'] = df['Mileage'].fillna(df['Mileage'].mode()[0])
df['Engine'] = df['Engine'].fillna(df['Engine'].mode()[0])
df['Power'] = df['Power'].fillna(df['Power'].mode()[0])

df['Seats'] = df['Seats'].fillna(df['Seats'].mode()[0])

# chack again
df.isnull().sum()

Unnamed: 0           0
Name                 0
Location             0
Year                 0
Kilometers_Driven    0
Fuel_Type            0
Transmission         0
Owner_Type           0
Mileage              0
Engine               0
Power                0
Seats                0
Price                0
dtype: int64

Q1, 2) : Regular expressions were used to extract only the numeric values from columns such as Mileage, Engine, and Power. This approach ensures that different unit formats (e.g., kmpl and km/kg) are handled consistently before converting the data into numeric format.

In [5]:
df['Power'] = df['Power'].replace('null bhp', None)

In [6]:
df['Mileage'] = df['Mileage'].str.extract(r'(\d+\.?\d*)')
df['Engine'] = df['Engine'].str.extract(r'(\d+\.?\d*)')
df['Power'] = df['Power'].str.extract(r'(\d+\.?\d*)')

In [7]:
df['Mileage'] = pd.to_numeric(df['Mileage'])
df['Engine'] = pd.to_numeric(df['Engine'])
df['Power'] = pd.to_numeric(df['Power'])

In [8]:
df[['Mileage','Engine','Power']].isna().sum()

Mileage    0
Engine     0
Power      0
dtype: int64

Q1, 3) : Categorical variables were converted into numerical format using one-hot encoding. Each category was transformed into binary indicator variables (0/1) to make the dataset suitable for machine learning models.

In [9]:
df[['Fuel_Type','Transmission','Owner_Type']].head()

  Fuel_Type Transmission Owner_Type
0    Diesel       Manual      First
1    Petrol       Manual      First
2    Diesel       Manual      First
3    Diesel    Automatic     Second
4    Diesel       Manual      First

In [10]:
df_encoded = pd.get_dummies(
    df,
    columns=['Fuel_Type', 'Transmission'],
    dtype=int
)

In [11]:
df_encoded.head()

,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Owner_Type,Mileage,Engine,Power,Seats,Price,Fuel_Type_Diesel,Fuel_Type_Electric,Fuel_Type_Petrol,Transmission_Automatic,Transmission_Manual
0,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,First,19.67,1582,126.20,5.0,12.50,1,0,0,0,1
1,2,Honda Jazz V,Chennai,2011,46000,First,13.00,1199,88.70,5.0,4.50,0,0,1,0,1
2,3,Maruti Ertiga VDI,Chennai,2012,87000,First,20.77,1248,88.76,7.0,6.00,1,0,0,0,1
3,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Second,15.20,1968,140.80,5.0,17.74,1,0,0,1,0
4,6,Nissan Micra Diesel XV,Jaipur,2013,86999,First,23.08,1461,63.10,5.0,3.50,1,0,0,0,1

In [12]:
df_encoded.shape

(5847, 16)

Q1, d) :  calculate the current age of the car

In [13]:
current_year = 2026
df_encoded['Car_Age'] = current_year - df_encoded['Year']

In [14]:
df_encoded[['Year', 'Car_Age']].head()

   Year  Car_Age
0  2015       11
1  2011       15
2  2012       14
3  2013       13
4  2013       13

In [15]:
df_encoded['Car_Age'].describe()

count    5847.000000
mean       12.551565
std         3.194949
min         7.000000
25%        10.000000
50%        12.000000
75%        14.000000
max        28.000000
Name: Car_Age, dtype: float64

Q1, e)

In [16]:
df_sel = df_encoded[['Name', 'Year', 'Car_Age', 'Kilometers_Driven', 'Price', 'Mileage']]
df_sel.head()

,Name,Year,Car_Age,Kilometers_Driven,Price,Mileage
0,Hyundai Creta 1.6 CRDi SX Option,2015,11,41000,12.50,19.67
1,Honda Jazz V,2011,15,46000,4.50,13.00
2,Maruti Ertiga VDI,2012,14,87000,6.00,20.77
3,Audi A4 New 2.0 TDI Multitronic,2013,13,40670,17.74,15.20
4,Nissan Micra Diesel XV,2013,13,86999,3.50,23.08

In [17]:
df_filtered = df_encoded[df_encoded['Car_Age'] <= 10]
df_filtered.head()

,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Owner_Type,Mileage,Engine,Power,Seats,Price,Fuel_Type_Diesel,Fuel_Type_Electric,Fuel_Type_Petrol,Transmission_Automatic,Transmission_Manual,Car_Age
5,7,Toyota Innova Crysta 2.8 GX AT 8S,Mumbai,2016,36000,First,11.36,2755,171.50,8.0,17.50,1,0,0,1,0,10
8,10,Maruti Ciaz Zeta,Kochi,2018,25692,First,21.56,1462,103.25,5.0,9.95,0,0,1,0,1,8
14,16,Honda Amaze S i-Dtech,Kochi,2016,58950,First,25.80,1498,98.60,5.0,5.40,1,0,0,0,1,10
15,17,Maruti Swift DDiS VDI,Jaipur,2017,25000,First,28.40,1248,74.00,5.0,5.99,1,0,0,0,1,9
26,28,Honda WRV i-VTEC VX,Kochi,2018,37430,First,17.50,1199,88.70,5.0,9.90,0,0,1,0,1,8

In [18]:
df_renamed = df_filtered.rename(columns={
    'Kilometers_Driven': 'KM_Driven',
    'Car_Age': 'Age_of_Car'
})
df_renamed.head()

,Unnamed: 0,Name,Location,Year,KM_Driven,Owner_Type,Mileage,Engine,Power,Seats,Price,Fuel_Type_Diesel,Fuel_Type_Electric,Fuel_Type_Petrol,Transmission_Automatic,Transmission_Manual,Age_of_Car
5,7,Toyota Innova Crysta 2.8 GX AT 8S,Mumbai,2016,36000,First,11.36,2755,171.50,8.0,17.50,1,0,0,1,0,10
8,10,Maruti Ciaz Zeta,Kochi,2018,25692,First,21.56,1462,103.25,5.0,9.95,0,0,1,0,1,8
14,16,Honda Amaze S i-Dtech,Kochi,2016,58950,First,25.80,1498,98.60,5.0,5.40,1,0,0,0,1,10
15,17,Maruti Swift DDiS VDI,Jaipur,2017,25000,First,28.40,1248,74.00,5.0,5.99,1,0,0,0,1,9
26,28,Honda WRV i-VTEC VX,Kochi,2018,37430,First,17.50,1199,88.70,5.0,9.90,0,0,1,0,1,8

In [19]:
df_renamed['Price_per_KM'] = df_renamed['Price'] / (df_renamed['KM_Driven'] + 1)
df_renamed.head()

,Unnamed: 0,Name,Location,Year,KM_Driven,Owner_Type,Mileage,Engine,Power,Seats,Price,Fuel_Type_Diesel,Fuel_Type_Electric,Fuel_Type_Petrol,Transmission_Automatic,Transmission_Manual,Age_of_Car,Price_per_KM
5,7,Toyota Innova Crysta 2.8 GX AT 8S,Mumbai,2016,36000,First,11.36,2755,171.50,8.0,17.50,1,0,0,1,0,10,0.000486
8,10,Maruti Ciaz Zeta,Kochi,2018,25692,First,21.56,1462,103.25,5.0,9.95,0,0,1,0,1,8,0.000387
14,16,Honda Amaze S i-Dtech,Kochi,2016,58950,First,25.80,1498,98.60,5.0,5.40,1,0,0,0,1,10,0.000092
15,17,Maruti Swift DDiS VDI,Jaipur,2017,25000,First,28.40,1248,74.00,5.0,5.99,1,0,0,0,1,9,0.000240
26,28,Honda WRV i-VTEC VX,Kochi,2018,37430,First,17.50,1199,88.70,5.0,9.90,0,0,1,0,1,8,0.000264

In [20]:
df_sorted = df_renamed.sort_values(by='Price', ascending=False)
df_sorted.head()

,Unnamed: 0,Name,Location,Year,KM_Driven,Owner_Type,Mileage,Engine,Power,Seats,Price,Fuel_Type_Diesel,Fuel_Type_Electric,Fuel_Type_Petrol,Transmission_Automatic,Transmission_Manual,Age_of_Car,Price_per_KM
3952,4079,Land Rover Range Rover 3.0 Diesel LWB Vogue,Hyderabad,2017,25000,First,13.33,2993,255.00,5.0,160.00,1,0,0,1,0,9,0.006400
1457,1505,Land Rover Range Rover Sport SE,Kochi,2019,26013,First,12.65,2993,255.00,5.0,97.07,1,0,0,1,0,7,0.003731
1917,1974,BMW 7 Series 740Li,Coimbatore,2018,28060,First,12.05,2979,320.00,5.0,93.67,0,0,1,1,0,8,0.003338
1927,1984,BMW 7 Series 740Li,Bangalore,2017,17465,First,12.05,2979,320.00,5.0,93.00,0,0,1,1,0,9,0.005325
2035,2095,Mercedes-Benz SLC 43 AMG,Coimbatore,2019,2526,First,19.00,2996,362.07,2.0,83.96,0,0,1,1,0,7,0.033225

In [23]:
df['Car_Age'] = 2026 - df['Year']

In [24]:
df_summary = df.groupby('Fuel_Type').agg({
    'Price': 'mean',
    'Car_Age': 'mean',
    'Kilometers_Driven': 'mean'
}).reset_index()

df_summary

  Fuel_Type      Price    Car_Age  Kilometers_Driven
0    Diesel  12.960686  12.209111       67464.220500
1  Electric  12.875000  12.500000       47000.000000
2    Petrol   5.756688  12.954918       47755.460507

All required data manipulation operations including select, filter, rename, mutate, arrange, and group-by summarize were successfully performed using pandas.